test-suite = "{{ manifest_dir }}/testcases/{{ bin_alias }}.yml"

[template]
src = '''
use proconio::{fastout, input};

#[fastout]
fn main() {
    input! {}
}
'''

[template.new]
dependencies = '''
#proconio = { version = "=0.3.6", features = ["derive"] }
'''
dev-dependencies = '''
#atcoder-202004-lock = { git = "https://github.com/qryxip/atcoder-202004-lock" }
'''

[template.new.copy-files]

[new]
kind = "oj-api"
url = "https://kenkoooo.com/atcoder/#/contest/show/{{ id }}"
path = "./{{ contest }}"

[test]
